# render.yaml

services:
  - type: web                  # tipo de serviço no Render
    name: tech-challenge1      # nome que aparecerá no dashboard
    env: python                # runtime Python
    region: oregon             # data center (ex: oregon, frankfurt, ireland…)
    branch: issue_7            # branch que dispara o build/deploy
    plan: free                 # plano de recurso (free, starter, pro…)
    healthCheckPath: "/health" # endpoint para health checks
    buildCommand: |            # comandos para instalar dependências
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: >            # comando para iniciar seu FastAPI
      gunicorn main:app
      -k uvicorn.workers.UvicornWorker
      -b 0.0.0.0:$PORT
    envVars:                    # variáveis de ambiente
      - key: PYTHON_VERSION
        value: 3.10.12      
      - key: SECRET_KEY
        value: JWT_PLACEHOLDER      
      - key: DB_DATABASE_URL
        value: sqlite:///./dados_embrapa.db
      - key: PORT
        value: "10000"              # opcional, só para tornar explícito
